version: '3.3'

services:
  web:
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 #python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=abc123
      - POSTGRES_DB=datavent

volumes:
  postgres_data:
