CREATE TABLE product ( 
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50),
    description varchar(400),
    price money,
    create_date timestamp DEFAULT CURRENT_TIMESTAMP
);